java_test(
    name = "TestSolution",
    srcs = ["TestSolution.java"],
    test_class = "com.jkurapati.sudoku.solve.TestSolution",
    deps = [
        "//src/main/java/com/jkurapati/sudoku/solve:Solution",
        "@maven//:junit_junit",
    ],
)
