java_test(
    name = "Solution",
    srcs = ["TestSolution.java"],
    test_class = "com.jkurapati.sudoku.solve.TestSolution",
    deps = [
        "//src/main/java/com/jkurapati/sudoku/solve:Solution",
#        "//third_party:junit4",
        "@maven//:junit_junit",
#        "//:java_test_deps",
    ],
)
