package(default_visibility = ["//visibility:public"])

java_library(
    name = "Solution",
    srcs = glob(["*.java"]),
)

#filegroup(
#    name = "srcs",
#    srcs = ["BUILD"] + glob(["**/*.java"]),
#)
